export const actions = {
  profile: {
    PROFILE_DATA_FETCHING: "PROFILE_DATA_FETCHING",
    PROFILE_DATA_FETCHED: "PROFILE_DATA_FETCHED",
    PROFILE_DATA_FETCHING_ERROR: "PROFILE_DATA_FETCHING_ERROR",
    PROFILE_DATA_EDITING:"PROFILE_DATA_EDITING",
    PROFILE_IMAGE_EDITING:"PROFILE_IMAGE_EDITING",
  },
  post: {
    POST_DATA_FETCHING: "POST_DATA_FETCHING",
    POST_DATA_FETCHED: "POST_DATA_FETCHED",
    POST_DATA_FETCHING_ERROR: "POST_DATA_FETCHING_ERROR",
    POST_DATA_EDITING:"POST_DATA_EDITING",
    POST_IMAGE_EDITING:"POST_IMAGE_EDITING",
  },
};
