export const actions = {
  profile: {
    PROFILE_DATA_FETCHING: "PROFILE_DATA_FETCHING",
    PROFILE_DATA_FETCHED: "PROFILE_DATA_FETCHED",
    PROFILE_DATA_FETCHING_ERROR: "PROFILE_DATA_FETCHING_ERROR",
    PROFILE_DATA_EDITING:"PROFILE_DATA_EDITING",
    PROFILE_IMAGE_EDITING:"PROFILE_IMAGE_EDITING",
  },
};
